### ISSUE TITLE
Web应用系统开发

### ISSUE THREAD

**Issue by Maple-se** [YongzeYang/NPU-U14M11103-Web-Application-Development-Technology#1]
学长，请问你这门课的实验课资料还在吗？，我看在这个仓库里只有实验说明，没有实验内容什么的

**Comment by YongzeYang** [comment]
这些实验有点久远了，我确实找不到那个时候的资料了。不过这些实验我记得不难，就是技术栈有点老（jsp+servlet已经被淘汰了）

**Comment by Maple-se** [comment]
okok感谢学长
